### PR TITLE
Updated documentation for lcd functions, especially color related

### PR DESCRIPTION
**Pull request by jfrickmann**
Added documentation for new colors and new functions

### CODE REVIEW

**Comment by pfeerick** [comment]
I'm going to merge this, and then update and run the script again as I just noticed I didn't update it after migrating it from my account to EdgeTX org... Hopefully nothing breaks along the way as this is still all new to me! And thank you! :)

**Comment by jfrickmann** [comment]
Strange - it looks like it updated newly added function like e.g. lcd.drawAnnulus and lcd.sizeText, but it did not update existing functions like e.g. lcd.RGB.
Git is soo much fun 🙄

**Comment by jfrickmann** [comment]
Wait, did you run the Python script locally before pushing? If you did that with the old source code files, then it would overwrite my new files with the old versions for the old files and leave the new files as is. Could that be what happened?

**Comment by pfeerick** [comment]
I don't think so... I'd pulled the repo after merging the PR, and once gitbooks had finished it's build as well, so it should have been working with the current state of the source files (although I do still need to push the updated url again as I didn't add that). Because of that, a lot of the files it only did minor changes, i.e. adding the -generated by script- warning on the top, as well as changing the header indent for some reason... script seems to seems to prefer level 2 and level 4 headings, and certain amounts of whitespace... that can probably be fixed, but it doesn't seem to cause any problems with gitbooks... s It seems your run didn't update everything it should have. e.g. https://github.com/EdgeTX/lua-reference-guide/blob/edgetx_2.4/part_iii_-_opentx_lua_api_reference/general-functions-less-than-greater-than-luadoc-begin-general/accesstelemetrypush.md was never touched... (check the history for the file at the top right)... 

Ok, some of the changes are because of the merge of the colour API stuff, so that's fine. Some I can't explain as the script does some weird stuff. I think the rest is because the API comments in the edgeTX source are still wrong, so as the warning suggests... further runs of the script will over-write all changes made... to the parts of the documentation it generates... they need to be fixed at in the source. 

Does the python script also need poking, as I see it's not parsing `api_lcd.cpp` and `api_stdlcd.cpp` ... 

https://github.com/EdgeTX/lua-reference-guide/blob/fe42fe461fcccd828fba5d218da01336e4f7b0cd/tools/generate-api-docs.py#L281

I can either revert the changes I pushed, reverting it to the PR state, or look at getting the source file comments updated, open to suggestions...

**Comment by jfrickmann** [comment]
This PR deals with lcd functions, so never mind model functions and general API. 

Since I updated things in the color API, I ran the Python script on api_colorlcd.cpp. If you run it on api_lcd.cpp or api_stdlcd.cpp after that, then it will overwrite the more current versions.

So please try again, and run the python script on api_colorlcd.cpp last. Or just pull in the files as they are in my PR without running the script yourself 😎

**Comment by pfeerick** [comment]
I was going to simply revert the changes, but probably can't now due to the changes made on gitbook... so will have to do that manually now. At the same time, I see why some of the changes are happening  - it seems there is a difference in opinion between between gitbooks and the generator script as to formatting of some things - if you have a  [look at the commit](https://github.com/EdgeTX/lua-reference-guide/commit/cbaaac8e7fc59e686901a87f66e29aba02c27488) from some of the changes you just made on gitbook... you can see the header markdown levels have changed and the comment about the file being script generated has been stripped, as well as "escaping" of brackets.

**Comment by pfeerick** [comment]
Ha! You know what the problem was?

https://github.com/EdgeTX/lua-reference-guide/blob/2c4596e02006c8ac7d351fcd785fdfc7a93ce548/tools/generate-api-docs.py#L25

**Comment by jfrickmann** [comment]
Ha ha, good catch! 

I can see that Lcd functions overview has been changed back (I moved the constants to Constants) and that the links in the files are broken. 

But we are getting closer, and I will just go through it on GitBook and fix it.

**Comment by pfeerick** [comment]
Sorry! I'm going to leave the python script alone for a while... and focus on using gitbooks natively as thanks to an issue raised by JIMB40 whereby I realised that gitbooks isn't always picking up changes on github... so it can be easier to generate the files locally and then import them into gitbooks, thereby using gitbooks first and foremost.

**Comment by jfrickmann** [comment]
I agree, let's dump the python script for now and just work on GitBook!

**Pull request merged**
